name: Cypress Test

on: [push]

env:
  CYPRESS_baseUrl: https://www.iddaa.com

jobs:
  cypress_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm ci

    - name: Run tests with Cypress
      run: |
        $(npm bin)/cypress run
